name: rewild
description: ReWild is a full-featured mobile application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.4
  path_provider: ^2.1.1
  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.2.3
  grpc: ^3.2.4
  android_id: ^0.3.5
  connectivity_plus: ^4.0.2
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.7
  fixnum: ^1.1.0
  google_nav_bar: ^5.0.6
  url_launcher: ^6.1.14
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  pie_chart: ^5.3.2
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_slidable: ^3.0.0
  sqflite: ^2.3.0
  share_plus: ^7.2.1
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  fl_chart: ^0.64.0
  cupertino_icons: ^1.0.2
  workmanager: ^0.5.2
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "assets/images/app.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
